CREATE TABLE PUBLIC.CONTAINER_AMOUNT_MAP (
	CONTAINER VARCHAR(255) NOT NULL,
AMOUNT INTEGER NOT NULL,
CONSTRAINT CONSTRAINT_F PRIMARY KEY (CONTAINER)
);

CREATE SEQUENCE SEQ_SETTING;

CREATE TABLE PUBLIC.SETTING (
	ID BIGINT DEFAULT NEXT VALUE FOR "PUBLIC"."SEQ_SETTING" NOT NULL AUTO_INCREMENT,
	COMPANY_NAME VARCHAR(255) NOT NULL,
	COMPANY_NUMBER VARCHAR(255) NOT NULL,
	CURRENT_YEAR VARCHAR(255),
	DELETED_AT DATE,
	HOME_DIRECTORY VARCHAR(255),
CONSTRAINT CONSTRAINT_A PRIMARY KEY (ID)
);

CREATE SEQUENCE SEQ_WINE;

CREATE TABLE PUBLIC.WINE (
	ID BIGINT DEFAULT NEXT VALUE FOR "PUBLIC"."SEQ_WINE" NOT NULL AUTO_INCREMENT,
	NAME VARCHAR(255) NOT NULL,
"YEAR" VARCHAR(255) NOT NULL,
CONSTRAINT CONSTRAINT_2 PRIMARY KEY (ID)
);

CREATE SEQUENCE SEQ_MEASURE;

CREATE TABLE PUBLIC.MEASURE (
  ID BIGINT DEFAULT NEXT VALUE FOR "PUBLIC"."SEQ_MEASURE" NOT NULL AUTO_INCREMENT,
MEASURE_TYPE INTEGER,
NAME VARCHAR(255) NOT NULL,
PARENT_ID BIGINT,
CONSTRAINT CONSTRAINT_6 PRIMARY KEY (ID),
CONSTRAINT FK_4KRDPPDHEOAGG74JVGFSML1U9 FOREIGN KEY (PARENT_ID) REFERENCES PUBLIC.MEASURE(ID) ON DELETE RESTRICT ON UPDATE RESTRICT
);

CREATE SEQUENCE SEQ_ENTRY;

CREATE TABLE PUBLIC.ENTRY (
	ID BIGINT DEFAULT NEXT VALUE FOR "PUBLIC"."SEQ_ENTRY" NOT NULL AUTO_INCREMENT,
	ADDITIONAL_INFORMATION VARCHAR(255),
AMOUNT INTEGER NOT NULL,
CONTAINER VARCHAR(255) NOT NULL,
CREATEDAT DATE,
REALIZEDAT DATE NOT NULL,
MEASURE_ID BIGINT,
WINE_ID BIGINT,
CONSTRAINT CONSTRAINT_3 PRIMARY KEY (ID),
CONSTRAINT FK_P0O74HUGCMCP227RWYT2VVGB3 FOREIGN KEY (MEASURE_ID) REFERENCES PUBLIC.MEASURE(ID) ON DELETE RESTRICT ON UPDATE RESTRICT,
CONSTRAINT FK_QEBCX3HQ3DP84WQ56PEWYELO8 FOREIGN KEY (WINE_ID) REFERENCES PUBLIC.WINE(ID) ON DELETE RESTRICT ON UPDATE RESTRICT
);
--CREATE INDEX FK_P0O74HUGCMCP227RWYT2VVGB3_INDEX_3 ON PUBLIC.ENTRY (MEASURE_ID);
--CREATE INDEX FK_QEBCX3HQ3DP84WQ56PEWYELO8_INDEX_3 ON PUBLIC.ENTRY (WINE_ID);
--CREATE UNIQUE INDEX PRIMARY_KEY_3 ON PUBLIC.ENTRY (ID);

INSERT INTO SETTING (COMPANY_NAME, COMPANY_NUMBER, CURRENT_YEAR) VALUES ('Winzerhof Schwanzelberger', '1563157', '2020');

