INSERT INTO MEASURE (MEASURE_TYPE, NAME, PARENT_ID) VALUES (0, 'Schwefelung', null);
INSERT INTO MEASURE (MEASURE_TYPE, NAME, PARENT_ID) VALUES (0, 'Anreicherung', null);
INSERT INTO MEASURE (MEASURE_TYPE, NAME, PARENT_ID) VALUES (0, 'Schönung', null);
INSERT INTO MEASURE (MEASURE_TYPE, NAME, PARENT_ID) VALUES (0, 'Eiweisschönung', (SELECT ID FROM MEASURE WHERE NAME = 'Schönung'));
INSERT INTO MEASURE (MEASURE_TYPE, NAME, PARENT_ID) VALUES (0, 'Entsäuerung', null);
INSERT INTO MEASURE (MEASURE_TYPE, NAME, PARENT_ID) VALUES (1, 'Umfüllen', null);
INSERT INTO MEASURE (MEASURE_TYPE, NAME, PARENT_ID) VALUES (0, 'Vorfiltration', null);
INSERT INTO MEASURE (MEASURE_TYPE, NAME, PARENT_ID) VALUES (0, 'Flaschenfüllung', null);