INSERT INTO MEASURE (MEASURE_TYPE, NAME, PARENT_ID) VALUES (0, 'Schwefelung', null);
INSERT INTO MEASURE (MEASURE_TYPE, NAME, PARENT_ID) VALUES (0, 'Anreicherung', null);
INSERT INTO MEASURE (MEASURE_TYPE, NAME, PARENT_ID) VALUES (0, 'Schönung', null);
INSERT INTO MEASURE (MEASURE_TYPE, NAME, PARENT_ID) VALUES (0, 'Eiweisschönung', (SELECT ID FROM MEASURE WHERE NAME = 'Schönung'));
INSERT INTO MEASURE (MEASURE_TYPE, NAME, PARENT_ID) VALUES (0, 'Entsäuerung', null);
INSERT INTO MEASURE (MEASURE_TYPE, NAME, PARENT_ID) VALUES (1, 'Umfüllen', null);
INSERT INTO MEASURE (MEASURE_TYPE, NAME, PARENT_ID) VALUES (0, 'Vorfiltration', null);
INSERT INTO MEASURE (MEASURE_TYPE, NAME, PARENT_ID) VALUES (0, 'Flaschenfüllung', null);

INSERT INTO CONTAINER_TYPE (NAME) VALUES ('Kunststoff');
INSERT INTO CONTAINER_TYPE (NAME) VALUES ('Edelstahl');
INSERT INTO CONTAINER_TYPE (NAME) VALUES ('Holz');

INSERT INTO LOCATION (NAME) VALUES ('Droß');
INSERT INTO LOCATION (NAME) VALUES ('Stratzing');

INSERT INTO CONTAINER (DESIGNATION, CONTAINER_TYPE_ID, LOCATION_ID, CAPACITY, IS_ALWAYS_FULL_CONTAINER)
VALUES (
'Faß 1', (SELECT ID FROM CONTAINER_TYPE WHERE NAME = 'Kunststoff'),
(SELECT ID FROM LOCATION WHERE NAME = 'Stratzing'),
10000,
false
);

INSERT INTO CONTAINER (DESIGNATION, CONTAINER_TYPE_ID, LOCATION_ID, CAPACITY, IS_ALWAYS_FULL_CONTAINER)
VALUES (
'kleines Faß 1', (SELECT ID FROM CONTAINER_TYPE WHERE NAME = 'Kunststoff'),
(SELECT ID FROM LOCATION WHERE NAME = 'Droß'),
10000,
false
);

INSERT INTO CONTAINER (DESIGNATION, CONTAINER_TYPE_ID, LOCATION_ID, CAPACITY, IS_ALWAYS_FULL_CONTAINER)
VALUES (
'Rotwein 1', (SELECT ID FROM CONTAINER_TYPE WHERE NAME = 'Edelstahl'),
(SELECT ID FROM LOCATION WHERE NAME = 'Droß'),
10000,
false
);


INSERT INTO CONTAINER (DESIGNATION, CONTAINER_TYPE_ID, LOCATION_ID, CAPACITY, IS_ALWAYS_FULL_CONTAINER)
VALUES (
'Faß 2', (SELECT ID FROM CONTAINER_TYPE WHERE NAME = 'Kunststoff'),
(SELECT ID FROM LOCATION WHERE NAME = 'Stratzing'),
10000,
false
);